"""
Deterministic recommendation engine.

Every recommendation produced here is derived by an explicitly named rule from data
the scoring pipeline already computed. Nothing is generated by a language model and
nothing is invented: each item carries `source_rule`, and anything that points at
resume prose carries the verbatim `evidence_text` it was derived from so the frontend
can locate it in the PDF.

Ranking follows the integration brief: pillars are ordered by
(track weight x remaining headroom), so the highest-leverage fix surfaces first
rather than merely the lowest raw score.

Hard rules, enforced by construction:
  * No recommendation ever asks the candidate to invent, estimate or inflate a number.
    Copy says "add the metric you measured", never "add a 30% improvement".
  * Branch match is described as weighting context, never as an eligibility gate.
  * A PoR detection gap is reported as a detection gap, not as an absence of leadership.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from track_rules import (
    NUMERIC_SCOPE_DIMENSIONS,
    SCOPE_DIMENSIONS,
    SCOPE_PATTERNS,
    kind_from_label,
    line_kind,
    numeric_expected,
    WEAK_OWNERSHIP_VERBS,
    dilution_rules_for,
)
from por_substance import (
    DIMENSION_LABEL as POR_DIMENSION_LABEL,
    DIMENSION_PROMPT as POR_DIMENSION_PROMPT,
    extract as extract_por_substance,
    summarise as summarise_por,
)
from tracks import get_track

SEVERITY_HIGH = "HIGH"
SEVERITY_IMPORTANT = "IMPORTANT"
SEVERITY_POLISH = "POLISH"

# scorer_engine's pillar display names -> the key used in ROLE_WEIGHTS.
_WEIGHT_KEY_OVERRIDES = {
    "Coursework & SCOPE": "Coursework & SCOPE",
    "SCOPE Articulation": "SCOPE Articulation",
}

def _has_metric(text: str) -> bool:
    """A bullet carries a measured outcome — the EDGE dimension of SCOPE."""
    return bool(SCOPE_PATTERNS["EDGE"].search(text or ""))


def _weight_for(pillar: str, weights: Dict[str, float]) -> float:
    if pillar in weights:
        return weights[pillar]
    if pillar in _WEIGHT_KEY_OVERRIDES and _WEIGHT_KEY_OVERRIDES[pillar] in weights:
        return weights[_WEIGHT_KEY_OVERRIDES[pillar]]
    # Every track's project pillar carries a track-specific display label but is
    # weighted under the single "Projects & Depth" key.
    return weights.get("Projects & Depth", 0.0)


def _headroom_points(pillar: str, score: int, weights: Dict[str, float]) -> float:
    """Maximum overall-score movement still available in this pillar.

    Content pillars are 0-20, scaled x5 into a 0-100 content score, weighted by the
    track vector, and the composite is 85% content + 15% structure.
    """
    weight = _weight_for(pillar, weights)
    return round(weight * (20 - max(0, min(20, score))) * 5 * 0.85, 1)


def _structural_headroom(structural_score: int) -> float:
    return round((100 - max(0, min(100, structural_score))) * 0.15, 1)


def _impact_label(points: float, shared: bool = False, informational: bool = False) -> str:
    if points <= 0.05:
        # Two different reasons a finding can be worth zero points, and they mean
        # opposite things to the reader.
        return "No direct score impact" if informational else "No headroom left in this pillar"
    if shared:
        # Layout findings all draw on the same 15% structural component, so the pool is
        # stated as shared rather than implying each item adds the full amount.
        return f"Shares up to +{points:.1f} of layout headroom"
    return f"Up to +{points:.1f} on the overall score"


class _Builder:
    def __init__(self, track: str, result: Dict[str, Any], weights: Dict[str, float]):
        self.track = track
        self.result = result
        self.weights = weights
        self.items: List[Dict[str, Any]] = []
        self._seq = 0

    def add(
        self,
        *,
        source_rule: str,
        severity: str,
        title: str,
        rationale: str,
        action: str,
        section: str,
        pillar: str,
        evidence_text: Optional[str] = None,
        # Pre-located page regions, for findings that are geometric rather than textual.
        evidence_regions: Optional[List[Dict[str, Any]]] = None,
        impact_points: Optional[float] = None,
        detail: Optional[Dict[str, Any]] = None,
        shared_impact: bool = False,
        informational: bool = False,
    ) -> None:
        self._seq += 1
        points = (
            impact_points
            if impact_points is not None
            else _headroom_points(pillar, self._pillar_score(pillar), self.weights)
        )
        self.items.append(
            {
                "id": f"rec-{self._seq:03d}-{source_rule.lower()}",
                "severity": severity,
                "title": title,
                "rationale": rationale,
                "action": action,
                "section": section,
                "pillar": pillar,
                "evidence_text": evidence_text,
                # A geometric finding arrives already located; a textual one is resolved
                # downstream by searching the PDF for `evidence_text`.
                "evidence_refs": list(evidence_regions or []),
                "source_rule": source_rule,
                "expected_impact": _impact_label(points, shared_impact, informational),
                "impact_points": points,
                "pillar_weight": _weight_for(pillar, self.weights),
                "detail": detail or {},
            }
        )

    def _pillar_score(self, pillar: str) -> int:
        entry = self.result.get("pillars", {}).get(pillar)
        if isinstance(entry, dict):
            return int(entry.get("score", 0) or 0)
        return 0


def _project_pillar_key(result: Dict[str, Any], track: str) -> str:
    label = get_track(track).project_pillar_label
    if label in result.get("pillars", {}):
        return label
    for key in result.get("pillars", {}):
        if key.startswith("Projects") or key.startswith("Core Projects"):
            return key
    return label


def _scope_pillar_key(result: Dict[str, Any]) -> str:
    return "Coursework & SCOPE" if "Coursework & SCOPE" in result.get("pillars", {}) else "SCOPE Articulation"


def _bullets(entries: List[Dict[str, Any]], title_key: str) -> List[tuple]:
    """
    (heading, bullet, printed_label) for each bullet worth assessing.

    `description_roles` runs parallel to `description` and holds the row label the
    resume printed — Objective, Approach or Result — or "" where none was given. It is
    read positionally and tolerates being short or absent, since older extractions and
    resumes that use no such table will not have it.
    """
    out = []
    for entry in entries or []:
        heading = (entry.get(title_key) or entry.get("organization") or "").strip()
        # Only a list is usable. A resume with no Objective / Approach / Result table
        # yields "" or no key at all, and a malformed value must degrade to inference
        # rather than be indexed character by character.
        roles = entry.get("description_roles")
        if not isinstance(roles, list):
            roles = []
        for index, bullet in enumerate(entry.get("description") or []):
            text = (bullet or "").strip()
            if len(text.split()) >= 5:
                label = roles[index] if index < len(roles) else None
                out.append((heading, text, label))
    return out


# ---------------------------------------------------------------- rules

def _rule_academics(b: _Builder) -> None:
    signals = b.result.get("extracted_signals", {})
    pillar = "Academics & CPI"
    score = b._pillar_score(pillar)
    if signals.get("cpi_status") == "UNVERIFIED_MISSING":
        b.add(
            source_rule="CPI_UNVERIFIED_MISSING",
            severity=SEVERITY_HIGH,
            title="Disclose your CPI in the academic qualifications table",
            rationale=(
                "No CPI or CGPA was found in the B.Tech row of the academic table, so the "
                f"academics pillar was scored at the unverified baseline of {score}/20 rather "
                "than on your actual standing."
            ),
            action=(
                "Add your current CPI to the grade column of the IIT Kanpur row, in the same "
                "X.XX format the SPO template uses."
            ),
            section="Academic Qualifications",
            pillar=pillar,
        )
        return

    cpi = signals.get("cpi")
    if cpi is not None and score < 14:
        b.add(
            source_rule="ACADEMICS_BELOW_TRACK_BAND",
            severity=SEVERITY_IMPORTANT,
            title="Academic signal sits below this track's band",
            rationale=(
                f"A CPI of {cpi} scores {score}/20 on the {b.track} academics band, and "
                f"academics carries {_weight_for(pillar, b.weights):.0%} of the content weight here."
            ),
            action=(
                "Surface the verified academic signals this band also credits and that may be "
                "missing from the resume: JEE Advanced AIR, an Academic Excellence Award, a named "
                "scholarship, an olympiad stage, or a rated competitive-programming profile."
            ),
            section="Scholastic Qualifications",
            pillar=pillar,
        )


def _rule_por(b: _Builder) -> None:
    signals = b.result.get("extracted_signals", {})
    resume = b.result.get("structured_resume", {})
    entries = resume.get("Position of Responsibility") or []
    pillar = "Leadership & PoR"
    tier = signals.get("por_tier")

    if tier == 8 and entries:
        # The Gymkhana hierarchy only covers posts the institute confers. A role outside
        # it is not an unrecognised PoR, it is a PoR the list does not cover — so it is
        # read on its substance rather than reported as a naming problem.
        first = entries[0]
        label = " — ".join(x for x in [first.get("position"), first.get("organization")] if x)
        substance = extract_por_substance(entries)
        present, missing = substance["present"], substance["missing"]

        shown = "; ".join(
            f"{POR_DIMENSION_LABEL[d].lower()} ({summarise_por(d, substance['dimensions'][d])})"
            for d in present
        )
        # The prompts are clauses containing commas, so they are joined with semicolons
        # rather than run together into one unpunctuated sentence.
        wants = [POR_DIMENSION_PROMPT[d] for d in missing]
        asked = (
            "" if not wants
            else wants[0] if len(wants) == 1
            else "; ".join(wants[:-1]) + "; and " + wants[-1]
        )

        if present and missing:
            rationale = (
                f"{label or 'This position'} already shows {shown}. What a recruiter reads next "
                "is the part that is not here yet."
            )
            action = f"State {asked}."
        elif present:
            rationale = (
                f"{label or 'This position'} shows {shown}. Span, resources and turnout are all "
                "evidenced, which is what a recruiter looks for beyond the title."
            )
            action = (
                "Keep these figures in the one-page version; they are what carry the role."
            )
        else:
            rationale = (
                f"{label or 'This position'} is described by title and body only. A recruiter "
                "reading a leadership role looks past the designation for what it involved."
            )
            action = f"State {asked}."

        complete = not missing
        b.add(
            source_rule="POR_SUBSTANCE_THIN",
            severity=SEVERITY_POLISH if len(present) >= 2 else SEVERITY_IMPORTANT,
            # Nothing is being asked for once all three are evidenced, so it must not be
            # titled as a shortfall.
            title=(
                "Position of responsibility is fully described"
                if complete
                else "Position of responsibility is described by title alone"
                if not present
                else "Position of responsibility could show more of what it involved"
            ),
            rationale=rationale,
            action=action,
            section="Position of Responsibility",
            pillar=pillar,
            evidence_text=(
                substance["dimensions"][present[0]][0]["evidence"] if present else label or None
            ),
            informational=complete,
            impact_points=0.0 if complete else None,
            detail={
                "por_dimensions_present": present,
                "por_dimensions_missing": missing,
            },
        )
    elif tier == 8 and not entries:
        weight = _weight_for(pillar, b.weights)
        b.add(
            source_rule="POR_ABSENT",
            severity=SEVERITY_HIGH if weight >= 0.2 else SEVERITY_IMPORTANT,
            title="No position of responsibility is listed",
            rationale=(
                f"The leadership pillar carries {weight:.0%} of the content weight on {b.track} "
                "and no PoR section was extracted from the resume."
            ),
            action=(
                "If you hold or have held a Gymkhana, club, fest or hall position, add it with the "
                "official designation and dates. If you genuinely hold none, do not add a "
                "placeholder — invest the space in the pillars that are still open."
            ),
            section="Position of Responsibility",
            pillar=pillar,
        )


def _scope_profile(text: str) -> Dict[str, bool]:
    profile = {dim: bool(pattern.search(text or "")) for dim, pattern in SCOPE_PATTERNS.items()}
    # "Worked on ..." is past tense but is explicitly a zero-ownership opener, so it
    # must not satisfy OWN on the strength of its morphology alone.
    if WEAK_OWNERSHIP_VERBS.search(text or ""):
        profile["OWN"] = False
    return profile


# Every section whose bullets describe work the candidate did. Competitions and
# research were previously left out, which meant the Inter-IIT style entries — the ones
# that actually label their rows Objective / Approach / Result — were never assessed.
_BULLET_SECTIONS = (
    ("Work Experience", "role"),
    ("Projects", "title"),
    ("Major Competitions", "competition"),
    ("Research Experience", "title"),
)


def _all_bullets(resume: Dict[str, Any]) -> List[tuple]:
    """(section, heading, bullet) across every section SCOPE is evaluated on."""
    out = []
    for section, key in _BULLET_SECTIONS:
        for heading, bullet, label in _bullets(resume.get(section), key):
            out.append((section, heading, bullet, label))
    return out


def _rule_scope_bullets(b: _Builder) -> None:
    """SCOPE bullet analysis.

    The role knowledge bases define SCOPE as Scale / Context / Own / Proof / Edge and
    evaluate every bullet against it. Rather than telling the candidate to "add metrics",
    this names the dimensions a specific bullet is missing.
    """
    resume = b.result.get("structured_resume", {})
    pillar = _scope_pillar_key(b.result)
    score = b._pillar_score(pillar)
    if score >= 18:
        return

    scored = []
    for section, heading, bullet, label in _all_bullets(resume):
        # What the resume printed beats what the sentence looks like.
        kind = kind_from_label(label) or line_kind(bullet)
        # A recognition is a matter of record — a PPO, a medal, a paper accepted. There
        # is no SCOPE advice to give about it, so it is not assessed at all.
        if kind == "RECOGNITION":
            continue

        profile = _scope_profile(bullet)
        # SCALE and EDGE are the two dimensions that ask for a figure, and only the
        # method and the outcome can carry one. An objective states intent; telling a
        # candidate to quantify "Built a system for X" asks for something that does not
        # exist. Those dimensions are dropped rather than counted as absent.
        if not numeric_expected(kind):
            for dim in NUMERIC_SCOPE_DIMENSIONS:
                profile.pop(dim, None)

        present = [d for d, ok in profile.items() if ok]
        missing = [d for d, ok in profile.items() if not ok]
        if not missing:
            continue

        # Rank on the share of applicable dimensions satisfied, not the raw count.
        #
        # An objective has only three dimensions in play once SCALE and EDGE are
        # dropped, so it scored 0-of-3 while a method line scored 1-of-5 — and under a
        # plain count the objective won every project, which is why the highlight always
        # landed on it. Approach and result lines are ordered ahead of it as well:
        # those are the ones a number can actually be added to.
        ratio = len(present) / len(profile) if profile else 1.0
        priority = 0 if numeric_expected(kind) else 1
        scored.append((priority, ratio, section, heading, bullet, missing, kind,
                       len(present), len(profile), list(profile)))

    if not scored:
        return

    scored.sort(key=lambda row: (row[0], row[1]))
    # One bullet per role/project, so the three suggestions span the resume rather than
    # landing three times on whichever entry happens to have the most bullets.
    weakest: List[tuple] = []
    seen_headings: set = set()
    for row in scored:
        if row[1] > 0.6 or len(weakest) >= 3:
            break
        heading = row[3]
        if heading in seen_headings:
            continue
        seen_headings.add(heading)
        weakest.append(row)

    for (_priority, _ratio, section, heading, bullet, missing, kind,
         present_count, applicable, applicable_dims) in weakest:
        # EDGE and SCALE are the two dimensions that most often separate tiers, so they
        # lead the copy when absent.
        lead = [d for d in ("EDGE", "SCALE", "PROOF", "CONTEXT", "OWN") if d in missing][:2]
        lead_text = " and ".join(SCOPE_DIMENSIONS[d].split(" — ")[0].lower() for d in lead)
        b.add(
            source_rule="SCOPE_BULLET_INCOMPLETE",
            severity=SEVERITY_HIGH if (score < 12 and _ratio <= 0.4) else SEVERITY_IMPORTANT,
            title=(
                f"Quantify the outcome in {heading}"
                if "EDGE" in missing and heading and numeric_expected(kind)
                else f"Strengthen this bullet in {heading or section}"
            ),
            rationale=(
                f"This line in {heading or section} is missing {lead_text}. "
                f"It reads as an activity description rather than a result a reviewer can size."
            ),
            action=_scope_action(lead),
            section=section,
            pillar=pillar,
            evidence_text=bullet,
            detail={
                # Dimensions that do not apply to this kind of line are neither
                # "present" nor "missing" — an objective is not judged on the two that
                # ask for a figure, so the totals are of what actually applied.
                "scope_present": [d for d in applicable_dims if d not in missing],
                "scope_missing": missing,
                "scope_covered": present_count,
                "scope_total": applicable,
                "line_kind": kind,
            },
        )


_SCOPE_ACTIONS = {
    "EDGE": "add the number you actually measured for the outcome",
    "SCALE": "state the size the work operated at — users, records, revenue, traffic or team",
    "PROOF": "say where it landed — merged, deployed, adopted, published or handed over",
    "CONTEXT": "name the real data, segment or constraint the work sat inside",
    "OWN": "open with the decision or design you personally made",
}


def _scope_action(missing: List[str]) -> str:
    parts = [_SCOPE_ACTIONS[d] for d in missing if d in _SCOPE_ACTIONS]
    if not parts:
        return "Rewrite the line so it states an outcome rather than an activity."
    joined = "; ".join(parts)
    return (
        f"Rewrite the line to {joined}. Use only figures you recorded during the work — "
        "if a number was never measured, describe what shipped instead of estimating one."
    )


def _rule_weak_verbs(b: _Builder) -> None:
    """consult.txt §4 lists the verbs that signal zero ownership. Applies to every track."""
    resume = b.result.get("structured_resume", {})
    pillar = _scope_pillar_key(b.result)
    offenders = [
        (section, heading, bullet)
        for section, heading, bullet, _label in _all_bullets(resume)
        if WEAK_OWNERSHIP_VERBS.search(bullet)
    ]
    for section, heading, bullet in offenders[:2]:
        opener = " ".join(bullet.split()[:3])
        b.add(
            source_rule="WEAK_OWNERSHIP_VERB",
            severity=SEVERITY_IMPORTANT,
            title=f"Bullet opens with \u201c{opener}\u2026\u201d",
            rationale=(
                "Openers such as 'worked on', 'was responsible for' and 'helped with' are listed "
                "as zero-ownership verbs; they leave what you personally decided undefined."
            ),
            action=(
                "Open with the action you took — architected, designed, negotiated, optimised, "
                "automated, launched — followed by the thing you owned."
            ),
            section=section,
            pillar=pillar,
            evidence_text=bullet,
        )


def _rule_dilution(b: _Builder) -> None:
    """Track-specific red flags, each transcribed from that track's knowledge base."""
    resume = b.result.get("structured_resume", {})
    scan_targets = {
        "bullets": [(s, h, t) for s, h, t, _lbl in _all_bullets(resume)],
        "skills": [("Technical Skills", "Technical Skills", " ".join(resume.get("Technical Skills") or []))],
        "extra_curricular": [
            ("Extra Curricular Activities", "Extra Curricular Activities", t)
            for t in (resume.get("Extra Curricular Activities") or [])
            if isinstance(t, str)
        ],
    }

    for rule in dilution_rules_for(b.track):
        for section, heading, text in scan_targets.get(rule.scan, []):
            if not text or not rule.pattern.search(text):
                continue
            b.add(
                source_rule=rule.rule_id,
                severity=SEVERITY_IMPORTANT,
                title=rule.title,
                rationale=rule.rationale,
                action=rule.action,
                section=section,
                pillar=_project_pillar_key(b.result, b.track),
                evidence_text=text,
                impact_points=0.0,
                informational=True,
                detail={"knowledge_base": rule.kb_section},
            )
            break  # one finding per rule; the first instance is the citation


def _rule_work_experience(b: _Builder) -> None:
    resume = b.result.get("structured_resume", {})
    entries = resume.get("Work Experience") or []
    pillar = "Work Experience"
    score = b._pillar_score(pillar)
    weight = _weight_for(pillar, b.weights)

    if not entries:
        b.add(
            source_rule="WORK_EXPERIENCE_ABSENT",
            severity=SEVERITY_HIGH,
            title="No work experience section was extracted",
            rationale=(
                f"Work experience is weighted at {weight:.0%} for {b.track} and nothing was found "
                "under that heading."
            ),
            action=(
                "If you have completed an internship or a paid engagement, add it under a heading "
                "the parser recognises as 'Work Experience' with organisation, role and duration."
            ),
            section="Work Experience",
            pillar=pillar,
        )
        return

    if score < 14:
        reasoning = (b.result.get("pillars", {}).get(pillar, {}) or {}).get("reasoning")
        b.add(
            source_rule="WORK_EXPERIENCE_BELOW_BAND",
            severity=SEVERITY_HIGH if weight >= 0.25 else SEVERITY_IMPORTANT,
            title="Work experience is scoring below the shortlist band",
            rationale=(
                f"The work-experience pillar scored {score}/20 against this track's rubric and "
                f"carries {weight:.0%} of the content weight, the largest weighted gap available."
            ),
            detail={"engine_reasoning": (reasoning or "").strip() or None},
            action=(
                "Lead each role with the system or decision you owned rather than the tooling you "
                "used, and name the scale it operated at."
            ),
            section="Work Experience",
            pillar=pillar,
            evidence_text=(entries[0].get("description") or [None])[0],
        )


def _rule_projects(b: _Builder) -> None:
    resume = b.result.get("structured_resume", {})
    pillar = _project_pillar_key(b.result, b.track)
    score = b._pillar_score(pillar)
    projects = resume.get("Projects") or []

    if score >= 16:
        return

    reasoning = (b.result.get("pillars", {}).get(pillar, {}) or {}).get("reasoning")
    b.add(
        source_rule="PROJECT_DEPTH_BELOW_BAND",
        severity=SEVERITY_HIGH if score < 12 else SEVERITY_IMPORTANT,
        title=f"{pillar} has the most weighted headroom left"
        if _headroom_points(pillar, score, b.weights) >= 3
        else f"{pillar} is below the strong band",
        rationale=f"The project pillar scored {score}/20 against the {b.track} rubric.",
        detail={"engine_reasoning": (reasoning or "").strip() or None},
        action=(
            "Expand the single most relevant project into the depth the rubric asks for: the "
            "problem constraint, the approach you chose over an alternative, and the evaluated result."
        ),
        section="Projects",
        pillar=pillar,
        evidence_text=(projects[0].get("description") or [None])[0] if projects else None,
    )


def _rule_branch(b: _Builder) -> None:
    pillar = "Branch Match"
    score = b._pillar_score(pillar)
    weight = _weight_for(pillar, b.weights)
    branch = b.result.get("extracted_signals", {}).get("branch")
    if score >= 16 or weight < 0.05:
        return

    # Branch is fixed. This is framed as reweighting context, never as eligibility.
    open_pillars = sorted(
        (
            (p, _headroom_points(p, (v or {}).get("score", 0), b.weights))
            for p, v in b.result.get("pillars", {}).items()
            if p != pillar
        ),
        key=lambda kv: kv[1],
        reverse=True,
    )[:2]
    names = " and ".join(p for p, _ in open_pillars)

    b.add(
        source_rule="BRANCH_MATCH_CONTEXT",
        severity=SEVERITY_POLISH,
        title="Branch match is capped for this track",
        rationale=(
            f"Branch match scored {score}/20 for {branch} on {b.track} and carries {weight:.0%} of "
            "the content weight. Your branch is fixed, so this is context for where the remaining "
            "effort pays, not something to act on directly."
        ),
        action=f"Treat {names} as the pillars carrying your profile on this track.",
        section="Academic Qualifications",
        pillar=pillar,
        impact_points=0.0,
    )


_LAYOUT_RULES = [
    (
        "margins",
        "LAYOUT_MARGINS_TIGHT",
        "Page margins are tighter than the SPO guideline",
        "Widen the page margins to the SPO minimum; the layout pillar is 15% of the composite score.",
    ),
    (
        "font_size",
        "LAYOUT_FONT_SIZE_SMALL",
        "Body font size is below the SPO baseline",
        "Raise the smallest body size to the SPO baseline and cut a line elsewhere to make room.",
    ),
    (
        "font_families",
        "LAYOUT_FONT_FAMILIES",
        "More font families than the SPO guideline allows",
        "Consolidate onto the LaTeX Computer Modern family the SPO template ships with.",
    ),
    (
        "word_count",
        "LAYOUT_WORD_COUNT",
        "Word count is outside the SPO band",
        "Bring the total word count inside the SPO band shown in the layout panel.",
    ),
    (
        "name_ratio",
        "LAYOUT_NAME_RATIO",
        "Name header is smaller than 2.0x body text",
        "Increase the name header until it is at least twice the body font size.",
    ),
    (
        "whitespace",
        "LAYOUT_WHITESPACE",
        "Whitespace is outside the SPO band",
        "Rebalance the page: either bring content up to fill it, or open up the line "
        "spacing so the text block is not crammed.",
    ),
    (
        # 30% of the structural score, the heaviest component. A second page costs 18
        # points on its own, so it needs a finding of its own.
        "page_count",
        "LAYOUT_PAGE_COUNT",
        "Resume runs longer than one page",
        "Cut the resume to a single page; page count carries 30% of the layout score.",
    ),
]


def _rule_layout(b: _Builder) -> None:
    metrics = b.result.get("spo_layout_metrics", {}) or {}
    structural = int(b.result.get("structural_score", 0) or 0)
    headroom = _structural_headroom(structural)
    if structural >= 95:
        return

    # Each component's measured cost, so a finding can say what it actually cost rather
    # than splitting the headroom evenly across every violation.
    # Where each layout problem is visible, measured from the same spans that produced
    # the score. A layout finding has no sentence to search for, so without this it is
    # the one kind of finding that can never point at anything.
    regions = b.result.get("spo_layout_regions") or {}
    breakdown = b.result.get("structural_breakdown") or {}
    cost_by_key = {
        c["key"]: c
        for c in breakdown.get("components", [])
        if isinstance(c, dict) and "key" in c
    }

    for key, rule, title, action in _LAYOUT_RULES:
        metric = metrics.get(key) or cost_by_key.get(key, {}).get("metric")
        if not isinstance(metric, dict):
            continue
        delta = metric.get("DELTA")
        if not isinstance(delta, (int, float)):
            continue
        violating = delta > 0 if key in ("font_families", "page_count") else delta < 0
        if key in ("word_count", "whitespace"):
            violating = delta != 0
        if not violating:
            continue

        component = cost_by_key.get(key)
        if component:
            # points_lost is on the 0-100 structural scale; the composite weights it 15%.
            lost = float(component["points_lost"])
            points = round(lost * 0.15, 1)
            sub = component["sub_score"]
            severity = (
                SEVERITY_IMPORTANT if sub < 50
                else SEVERITY_POLISH
            )
            detail = (
                f" Scores {sub}/100 on this component, giving up "
                f"{lost:g} of {component['points_available']:g} layout points."
            )
        else:
            points, severity, detail = headroom, SEVERITY_POLISH, ""
        b.add(
            source_rule=rule,
            severity=severity,
            title=title,
            rationale=(
                f"Measured {metric.get('ACTUAL_VALUE')} against the SPO guideline of "
                f"{metric.get('GUIDELINE_VALUE')}. {metric.get('note', '')}".strip()
                + detail
            ),
            action=action,
            section="Document layout",
            pillar="Structural Layout",
            impact_points=points,
            evidence_regions=regions.get(key) or [],
            shared_impact=True,
        )


def _rule_unverified_companies(b: _Builder, unverified: List[str]) -> None:
    """
    Employers with no campus record.

    This used to report the name as unresolved and suggest it had been garbled in
    extraction, which read as an accusation against the candidate's own employer. The
    knowledge graph only covers firms that recruit here; sitting outside it is a fact
    about that coverage. So the organisation is sized instead, and the finding says what
    it is rather than what the graph failed to find.
    """
    if not unverified:
        return
    profiles = b.result.get("company_profiles") or {}

    described = []
    for name in unverified:
        profile = profiles.get(name) or {}
        label = profile.get("label")
        note = (profile.get("note") or "").strip()
        if not label or profile.get("band") == "unrecognised":
            described.append(f"{name} could not be sized from public information")
        elif note:
            described.append(f"{name} — {label.lower()}, {note.rstrip('.')}")
        else:
            described.append(f"{name} — {label.lower()}")

    b.add(
        source_rule="UNVERIFIED_COMPANY",
        severity=SEVERITY_POLISH,
        title="Employer has no campus recruiting record here",
        rationale=(
            "; ".join(described)
            + ". The recruiter graph only covers firms that run a process at IIT Kanpur, so "
            "this affects how the role is matched to recruiters, not how it is scored."
        ),
        action=(
            "Nothing to change. If the organisation is better known by another name, using "
            "that name helps it match against recruiter records."
        ),
        section="Work Experience",
        pillar="Work Experience",
        impact_points=0.0,
        informational=True,
        evidence_text=unverified[0],
    )


_SEVERITY_ORDER = {SEVERITY_HIGH: 0, SEVERITY_IMPORTANT: 1, SEVERITY_POLISH: 2}


def build_recommendations(
    result: Dict[str, Any],
    track: str,
    weights: Dict[str, float],
    unverified_companies: Optional[List[str]] = None,
) -> List[Dict[str, Any]]:
    b = _Builder(track, result, weights)
    _rule_academics(b)
    _rule_work_experience(b)
    _rule_projects(b)
    _rule_scope_bullets(b)
    _rule_weak_verbs(b)
    _rule_dilution(b)
    _rule_por(b)
    _rule_unverified_companies(b, unverified_companies or [])
    _rule_branch(b)
    _rule_layout(b)

    # A rule's severity reflects how bad the finding is in isolation; the track weighting
    # decides how much it can actually move. A SCOPE gap worth 1.9 points on QUANT (5%
    # weight) must not outrank a project gap worth 6.4, so severity is capped by leverage.
    for item in b.items:
        if item["severity"] == SEVERITY_HIGH and item["impact_points"] < 2.0:
            item["severity"] = SEVERITY_IMPORTANT
        if item["severity"] == SEVERITY_IMPORTANT and item["impact_points"] < 0.5:
            item["severity"] = SEVERITY_POLISH

    b.items.sort(key=lambda r: (_SEVERITY_ORDER[r["severity"]], -r["impact_points"]))
    return b.items
