/**
 * Fixture service. Reachable only when VITE_USE_MOCK=true.
 *
 * The fixture is generated by `backend/tools/make_mock_fixture.py` from a fictional
 * resume: its layout metrics, hard signals, recommendations, compliance findings,
 * shortlist fit and PDF evidence coordinates are all produced by the real backend
 * modules against `public/sample-resume.pdf`. Only the three Gemini-scored pillars are
 * stand-in values. Every fixture carries `meta.is_mock = true`, and the dashboard
 * labels the session accordingly.
 */

import type { EvaluationResult, HealthResponse, TrackCode } from "../lib/types";
import { validateEvaluation } from "../lib/validate";
import fixture from "./mock-evaluation.json";

const STEP_DELAY_MS = 620;

export function mockHealth(): HealthResponse {
  return {
    status: "ok",
    engine_version: "spo-resume-intelligence/1.0 (fixture)",
    capabilities: {
      gemini_configured: false,
      knowledge_graph: true,
      kg_schema_version: "2.0",
      kg_company_count: 78,
    },
    limits: { max_upload_bytes: 8 * 1024 * 1024, accepted_mime_types: ["application/pdf"] },
    model: "mock (no model call)",
  };
}

export async function mockEvaluate({
  file,
  track,
  signal,
}: {
  file: File;
  track: TrackCode;
  signal?: AbortSignal;
}): Promise<EvaluationResult> {
  await new Promise<void>((resolve, reject) => {
    const timer = setTimeout(resolve, STEP_DELAY_MS * 4);
    signal?.addEventListener("abort", () => {
      clearTimeout(timer);
      reject(new DOMException("Aborted", "AbortError"));
    });
  });

  const result = validateEvaluation(fixture);

  // The fixture's evidence coordinates belong to the bundled sample PDF, so its own
  // track and filename are kept rather than the request's — relabelling it would make
  // the highlights point at a document that was never scored.
  // A fixture session is a deliberate demo mode, not a broken evaluation, so it must not
  // borrow the "Partial result — incomplete" banner. Its own notice carries the fact,
  // `meta.is_mock` stays true, and the header keeps its Fixture data chip.
  const notes = [
    `"${file.name}" was not scored. Every panel below describes the bundled sample resume.`,
  ];
  if (track !== result.track.code) {
    notes.push(
      `The fixture was scored for ${result.track.code}, so the ${track} weighting you ` +
        "selected is not reflected.",
    );
  }

  return {
    ...result,
    // Real warnings from the fixture are preserved; the mock adds none of its own.
    warnings: result.warnings,
    mockNotes: notes,
    evaluation_status: result.evaluation_status,
  } as EvaluationResult & { mockNotes: string[] };
}
